In [1]:
# Required Libraries
import pandas as pd
import numpy as np

In [2]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\abhil\appdata\local\programs\python\python313\lib\site-packages (9.5.0)

WARNING: Ignoring invalid distribution ~otebook (C:\Users\abhil\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~upyterlab (C:\Users\abhil\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~otebook (C:\Users\abhil\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~upyterlab (C:\Users\abhil\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~otebook (C:\Users\abhil\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~upyterlab (C:\Users\abhil\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import mysql.connector

In [4]:
# Connection Create
connection = mysql.connector.connect(
    host = 'localhost',
    user ='root',
    password = 'mysql123',
    database = 'ecommerce_analytics'
)

In [5]:
print(connection.is_connected())

True

In [6]:
# Cursor Create

cursor = connection.cursor()

In [7]:
query = 'select * from customers limit 10'

In [8]:
cursor.execute(query)

In [9]:
results = cursor.fetchall()

In [10]:
print(results)

[('C0001', 'Customer_0001', 'Male', 34, 'Mumbai', 'West', datetime.date(2023, 1, 21)), ('C0002', 'Customer_0002', 'Female', 26, 'Hyderabad', 'South', datetime.date(2025, 9, 10)), ('C0003', 'Customer_0003', 'Male', 50, 'Pune', 'West', datetime.date(2023, 11, 1)), ('C0004', 'Customer_0004', 'Male', 37, 'Bengaluru', 'South', datetime.date(2024, 1, 6)), ('C0005', 'Customer_0005', 'Male', 30, 'Chennai', 'South', datetime.date(2025, 5, 2)), ('C0006', 'Customer_0006', 'Female', 45, 'Jaipur', 'North', datetime.date(2024, 1, 19)), ('C0007', 'Customer_0007', 'Male', 46, 'Lucknow', 'North', datetime.date(2024, 3, 20)), ('C0008', 'Customer_0008', 'Male', 30, 'Bengaluru', 'South', datetime.date(2024, 2, 29)), ('C0009', 'Customer_0009', 'Male', 52, 'Hyderabad', 'South', datetime.date(2023, 6, 10)), ('C0010', 'Customer_0010', 'Female', 23, 'Ahmedabad', 'West', datetime.date(2024, 9, 20))]

In [11]:
results[:5]

[('C0001',
  'Customer_0001',
  'Male',
  34,
  'Mumbai',
  'West',
  datetime.date(2023, 1, 21)),
 ('C0002',
  'Customer_0002',
  'Female',
  26,
  'Hyderabad',
  'South',
  datetime.date(2025, 9, 10)),
 ('C0003',
  'Customer_0003',
  'Male',
  50,
  'Pune',
  'West',
  datetime.date(2023, 11, 1)),
 ('C0004',
  'Customer_0004',
  'Male',
  37,
  'Bengaluru',
  'South',
  datetime.date(2024, 1, 6)),
 ('C0005',
  'Customer_0005',
  'Male',
  30,
  'Chennai',
  'South',
  datetime.date(2025, 5, 2))]

In [12]:
customers = pd.read_sql('select * from customers',connection)

C:\Users\abhil\AppData\Local\Temp\ipykernel_5744\2346080575.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers = pd.read_sql('select * from customers',connection)

In [13]:
customers.head()

  CustomerID   CustomerName  Gender  Age       City Region  SignupDate
0      C0001  Customer_0001    Male   34     Mumbai   West  2023-01-21
1      C0002  Customer_0002  Female   26  Hyderabad  South  2025-09-10
2      C0003  Customer_0003    Male   50       Pune   West  2023-11-01
3      C0004  Customer_0004    Male   37  Bengaluru  South  2024-01-06
4      C0005  Customer_0005    Male   30    Chennai  South  2025-05-02

In [14]:
customers.shape

(1000, 7)

In [15]:
customers.columns

Index(['CustomerID', 'CustomerName', 'Gender', 'Age', 'City', 'Region',
       'SignupDate'],
      dtype='object')

In [16]:
customers.dtypes

CustomerID      object
CustomerName    object
Gender          object
Age              int64
City            object
Region          object
SignupDate      object
dtype: object

In [17]:
orders = pd.read_sql(
    "SELECT * FROM Orders",
    connection
)

C:\Users\abhil\AppData\Local\Temp\ipykernel_5744\841546596.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders = pd.read_sql(

In [18]:
orders.head()

  OrderID   OrderDate CustomerID PaymentMethod OrderStatus
0  O00001  2026-01-19      C0484           UPI   Delivered
1  O00002  2026-02-14      C0450   Credit Card   Delivered
2  O00003  2025-11-21      C0523   Credit Card   Delivered
3  O00004  2025-05-08      C0871           UPI   Delivered
4  O00005  2025-05-04      C0354   Net Banking   Delivered

In [19]:
orders.shape

(5000, 5)

In [20]:
order_details = pd.read_sql(
    "SELECT * FROM OrderDetails",
    connection
)

C:\Users\abhil\AppData\Local\Temp\ipykernel_5744\2291828879.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  order_details = pd.read_sql(

In [21]:
order_details.shape

(12558, 8)

In [22]:
products = pd.read_sql(
    "SELECT * FROM Products",
    connection
)

C:\Users\abhil\AppData\Local\Temp\ipykernel_5744\3230490635.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products = pd.read_sql(

In [23]:
products.shape

(82, 5)

In [24]:
returns = pd.read_sql(
    "SELECT * FROM Returns",
    connection
)

C:\Users\abhil\AppData\Local\Temp\ipykernel_5744\3646760255.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  returns = pd.read_sql(

In [25]:
returns.shape

(257, 4)

In [26]:
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Order Details:", order_details.shape)
print("Returns:", returns.shape)

Customers: (1000, 7)
Products: (82, 5)
Orders: (5000, 5)
Order Details: (12558, 8)
Returns: (257, 4)

In [27]:
query = """
SELECT
    SUM(od.SalesAmount) AS TotalRevenue,
    SUM(od.Profit) AS TotalProfit
FROM Orders o
JOIN OrderDetails od
    ON o.OrderID = od.OrderID
WHERE o.OrderStatus = 'Delivered';
"""

In [28]:
revenue_summary = pd.read_sql(
    query,
    connection
)

C:\Users\abhil\AppData\Local\Temp\ipykernel_5744\2716565187.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  revenue_summary = pd.read_sql(

In [29]:
revenue_summary

   TotalRevenue  TotalProfit
0  1.533119e+08  52519937.55

In [30]:
cursor.close()
connection.close()

In [31]:
# DataFrames Check
customers.shape

(1000, 7)

In [32]:
products.shape

(82, 5)

In [33]:
orders.shape

(5000, 5)

In [34]:
order_details.shape

(12558, 8)

In [35]:
returns.shape

(257, 4)

In [36]:
# First 5 Records

customers.head()

  CustomerID   CustomerName  Gender  Age       City Region  SignupDate
0      C0001  Customer_0001    Male   34     Mumbai   West  2023-01-21
1      C0002  Customer_0002  Female   26  Hyderabad  South  2025-09-10
2      C0003  Customer_0003    Male   50       Pune   West  2023-11-01
3      C0004  Customer_0004    Male   37  Bengaluru  South  2024-01-06
4      C0005  Customer_0005    Male   30    Chennai  South  2025-05-02

In [37]:
products.head()

  ProductID          ProductName     Category  CostPrice  SellingPrice
0     P0001  Wireless Headphones  Electronics     4840.0        8847.0
1     P0002  Wireless Headphones  Electronics     4745.0        8892.0
2     P0003  Wireless Headphones  Electronics      262.0         319.0
3     P0004          Smart Watch  Electronics     2528.0        3517.0
4     P0005          Smart Watch  Electronics      289.0         526.0

In [38]:
orders.head()

  OrderID   OrderDate CustomerID PaymentMethod OrderStatus
0  O00001  2026-01-19      C0484           UPI   Delivered
1  O00002  2026-02-14      C0450   Credit Card   Delivered
2  O00003  2025-11-21      C0523   Credit Card   Delivered
3  O00004  2025-05-08      C0871           UPI   Delivered
4  O00005  2025-05-04      C0354   Net Banking   Delivered

In [39]:
order_details.head()

,OrderDetailID,OrderID,ProductID,Quantity,UnitPrice,DiscountPct,SalesAmount,Profit
0,OD000001,O00001,P0014,4,10018.0,15.0,34061.20,12649.20
1,OD000002,O00001,P0063,3,5568.0,5.0,15868.80,6532.80
2,OD000003,O00002,P0030,1,10331.0,5.0,9814.45,3909.45
3,OD000004,O00002,P0027,4,4363.0,10.0,15706.80,2006.80
4,OD000005,O00003,P0040,2,6601.0,5.0,12541.90,4543.90

In [40]:
returns.head()

  ReturnID OrderID  ReturnDate   ReturnReason
0   R00001  O00016  1970-01-01        Damaged
1   R00002  O00078  1970-01-01  Wrong Product
2   R00003  O00088  1970-01-01     Size Issue
3   R00004  O00124  1970-01-01     Size Issue
4   R00005  O00125  1970-01-01  Late Delivery

In [41]:
# Data Types

orders.dtypes

OrderID          object
OrderDate        object
CustomerID       object
PaymentMethod    object
OrderStatus      object
dtype: object

In [42]:
# Date Conversion

orders["OrderDate"] = pd.to_datetime(orders["OrderDate"])

In [43]:
orders.dtypes

OrderID                  object
OrderDate        datetime64[ns]
CustomerID               object
PaymentMethod            object
OrderStatus              object
dtype: object

In [44]:
# Customer SignupDate
customers["SignupDate"] = pd.to_datetime(
    customers["SignupDate"]
)

In [45]:
customers.dtypes

CustomerID              object
CustomerName            object
Gender                  object
Age                      int64
City                    object
Region                  object
SignupDate      datetime64[ns]
dtype: object

In [46]:
# Missing Values
customers.isnull().sum()

CustomerID      0
CustomerName    0
Gender          0
Age             0
City            0
Region          0
SignupDate      0
dtype: int64

In [47]:
products.isnull().sum()

ProductID       0
ProductName     0
Category        0
CostPrice       0
SellingPrice    0
dtype: int64

In [48]:
orders.isnull().sum()

OrderID          0
OrderDate        0
CustomerID       0
PaymentMethod    0
OrderStatus      0
dtype: int64

In [49]:
order_details.isnull().sum()

OrderDetailID    0
OrderID          0
ProductID        0
Quantity         0
UnitPrice        0
DiscountPct      0
SalesAmount      0
Profit           0
dtype: int64

In [50]:
returns.isnull().sum()

ReturnID        0
OrderID         0
ReturnDate      0
ReturnReason    0
dtype: int64

In [51]:
# Duplicate Records

orders.duplicated().sum()

np.int64(0)

In [52]:
order_details.duplicated().sum()

np.int64(0)

In [53]:
customers.duplicated().sum()

np.int64(0)

In [54]:
# Primary Key Duplicate Check

customers["CustomerID"].duplicated().sum()

np.int64(0)

In [55]:
products["ProductID"].duplicated().sum()

np.int64(0)

In [56]:
orders["OrderID"].duplicated().sum()

np.int64(0)

In [57]:
# Numeric Data Check
order_details.describe()

           Quantity     UnitPrice   DiscountPct   SalesAmount        Profit
count  12558.000000  12558.000000  12558.000000  12558.000000  12558.000000
mean       2.501752   6272.299570     10.742156  14010.138708   4804.382457
std        1.119501   3461.536155      7.112802  10628.052040   4894.725391
min        1.000000    319.000000      0.000000    239.250000  -2048.000000
25%        2.000000   3416.000000      5.000000   5949.000000   1342.400000
50%        2.000000   6288.000000     10.000000  11210.400000   3215.600000
75%        4.000000   8847.000000     15.000000  20044.800000   6608.400000
max        4.000000  14270.000000     25.000000  57080.000000  30860.000000

In [58]:
# Impossible Values Check

order_details[order_details["Quantity"] <= 0]

Empty DataFrame
Columns: [OrderDetailID, OrderID, ProductID, Quantity, UnitPrice, DiscountPct, SalesAmount, Profit]
Index: []

In [59]:
order_details[
    (order_details["DiscountPct"] < 0) | (order_details["DiscountPct"] > 100)]

Empty DataFrame
Columns: [OrderDetailID, OrderID, ProductID, Quantity, UnitPrice, DiscountPct, SalesAmount, Profit]
Index: []

In [60]:
order_details[
    order_details["SalesAmount"] < 0
]

Empty DataFrame
Columns: [OrderDetailID, OrderID, ProductID, Quantity, UnitPrice, DiscountPct, SalesAmount, Profit]
Index: []

In [61]:
# Customer Age Validation

customers[
    (customers["Age"] < 18) |
    (customers["Age"] > 100)
]

# df = customers[(customers["Age"] >= 18) & (customers["Age"] <= 100)]

Empty DataFrame
Columns: [CustomerID, CustomerName, Gender, Age, City, Region, SignupDate]
Index: []

In [62]:
# Create Analytical Dataset

df = orders.merge(
    customers,
    on="CustomerID",
    how="left"
)

In [63]:
# Add OrderDetails

df = df.merge(
    order_details,
    on="OrderID",
    how="inner"
)

In [64]:
# Add Product Information

df = df.merge(
    products,
    on="ProductID",
    how="left"
)

In [65]:
df.shape

(12558, 22)

In [66]:
df.head()

,OrderID,OrderDate,CustomerID,PaymentMethod,OrderStatus,CustomerName,Gender,Age,City,Region,...,ProductID,Quantity,UnitPrice,DiscountPct,SalesAmount,Profit,ProductName,Category,CostPrice,SellingPrice
0,O00001,2026-01-19,C0484,UPI,Delivered,Customer_0484,Female,31,Pune,West,...,P0014,4,10018.0,15.0,34061.20,12649.20,Mouse,Electronics,5353.0,10018.0
1,O00001,2026-01-19,C0484,UPI,Delivered,Customer_0484,Female,31,Pune,West,...,P0063,3,5568.0,5.0,15868.80,6532.80,Shampoo,Beauty,3112.0,5568.0
2,O00002,2026-02-14,C0450,Credit Card,Delivered,Customer_0450,Female,23,Hyderabad,South,...,P0030,1,10331.0,5.0,9814.45,3909.45,Table Lamp,Home,5905.0,10331.0
3,O00002,2026-02-14,C0450,Credit Card,Delivered,Customer_0450,Female,23,Hyderabad,South,...,P0027,4,4363.0,10.0,15706.80,2006.80,Air Fryer,Home,3425.0,4363.0
4,O00003,2025-11-21,C0523,Credit Card,Delivered,Customer_0523,Female,60,Delhi,North,...,P0040,2,6601.0,5.0,12541.90,4543.90,T-Shirt,Fashion,3999.0,6601.0

In [67]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'PaymentMethod', 'OrderStatus',
       'CustomerName', 'Gender', 'Age', 'City', 'Region', 'SignupDate',
       'OrderDetailID', 'ProductID', 'Quantity', 'UnitPrice', 'DiscountPct',
       'SalesAmount', 'Profit', 'ProductName', 'Category', 'CostPrice',
       'SellingPrice'],
      dtype='object')

In [68]:
# Check Duplicate Order Details

df["OrderDetailID"].duplicated().sum()

np.int64(0)

In [69]:
# Create Useful Date Columns

df["Year"] = df["OrderDate"].dt.year

df["Month"] = df["OrderDate"].dt.month

df["MonthName"] = df["OrderDate"].dt.month_name()

df["YearMonth"] = df["OrderDate"].dt.to_period("M").astype(str)

In [70]:
# Profit Margin

df["ProfitMarginPct"] = (
    df["Profit"] /
    df["SalesAmount"]
) * 100

In [71]:
# Final Data Quality Check

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12558 entries, 0 to 12557
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          12558 non-null  object
 1   OrderDate        12558 non-null  datetime64[ns]
 2   CustomerID       12558 non-null  object
 3   PaymentMethod    12558 non-null  object
 4   OrderStatus      12558 non-null  object
 5   CustomerName     12558 non-null  object
 6   Gender           12558 non-null  object
 7   Age              12558 non-null  int64
 8   City             12558 non-null  object
 9   Region           12558 non-null  object
 10  SignupDate       12558 non-null  datetime64[ns]
 11  OrderDetailID    12558 non-null  object
 12  ProductID        12558 non-null  object
 13  Quantity         12558 non-null  int64
 14  UnitPrice        12558 non-null  float64
 15  DiscountPct      12558 non-null  float64
 16  SalesAmount      12558 non-null  float64
 17  Profit           12558 non-null  float64
 18  ProductName      12558 non-null  object
 19  Category         12558 non-null  object
 20  CostPrice        12558 non-null  float64
 21  SellingPrice     12558 non-null  float64
 22  Year             12558 non-null  int32
 23  Month            12558 non-null  int32
 24  MonthName        12558 non-null  object
 25  YearMonth        12558 non-null  object
 26  ProfitMarginPct  12558 non-null  float64
dtypes: datetime64[ns](2), float64(7), int32(2), int64(2), object(14)
memory usage: 2.5+ MB

In [72]:
df.isnull().sum()

OrderID            0
OrderDate          0
CustomerID         0
PaymentMethod      0
OrderStatus        0
CustomerName       0
Gender             0
Age                0
City               0
Region             0
SignupDate         0
OrderDetailID      0
ProductID          0
Quantity           0
UnitPrice          0
DiscountPct        0
SalesAmount        0
Profit             0
ProductName        0
Category           0
CostPrice          0
SellingPrice       0
Year               0
Month              0
MonthName          0
YearMonth          0
ProfitMarginPct    0
dtype: int64

In [73]:
df.duplicated().sum()

np.int64(0)

In [74]:
df.to_csv(
    "ecommerce_clean_data.csv",
    index=False
)